# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='login_reg_lobby.Player')),
            ],
        ),
        migrations.CreateModel(
            name='DevCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devcards', to='login_reg_lobby.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=45)),
                ('robber', models.BooleanField()),
                ('adjacent_fields', models.ManyToManyField(related_name='_field_adjacent_fields_+', to='main_game.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_game.Edge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='login_reg_lobby.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='login_reg_lobby.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjacent_fields', models.ManyToManyField(related_name='adjacent_vertices', to='main_game.Field')),
            ],
        ),
        migrations.AddField(
            model_name='settlement',
            name='vertex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_game.Vertex'),
        ),
        migrations.AddField(
            model_name='edge',
            name='adjacent_fields',
            field=models.ManyToManyField(related_name='adjacent_edges', to='main_game.Field'),
        ),
        migrations.AddField(
            model_name='edge',
            name='adjacent_vertices',
            field=models.ManyToManyField(related_name='adjacent_edges', to='main_game.Vertex'),
        ),
        migrations.AddField(
            model_name='city',
            name='vertex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_game.Vertex'),
        ),
    ]
