# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='player',
        ),
        migrations.RemoveField(
            model_name='city',
            name='vertex',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='adjacent_fields',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='adjacent_vertices',
        ),
        migrations.RemoveField(
            model_name='vertex',
            name='adjacent_fields',
        ),
        migrations.RemoveField(
            model_name='road',
            name='edge',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='vertex',
        ),
        migrations.AddField(
            model_name='field',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='adjacent_fields',
            field=models.ManyToManyField(related_name='adjacent_roads', to='main_game.Field'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='adjacent_fields',
            field=models.ManyToManyField(related_name='adjacent_settlements', to='main_game.Field'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='rank',
            field=models.CharField(default='normal', max_length=45),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Vertex',
        ),
    ]
