# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0002_auto_20180723_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='login_reg_lobby.Player'),
        ),
    ]
