# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0006_auto_20180724_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='adjacent_settlements',
            field=models.ManyToManyField(related_name='adjacent_roads', to='main_game.Settlement'),
        ),
    ]
