# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='brick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='lumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='sheep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='vic_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wheat',
            field=models.IntegerField(default=0),
        ),
    ]
