# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_index',
            field=models.IntegerField(null=True),
        ),
    ]
