from django.shortcuts import render, HttpResponse, redirect
from .models import *

def index(request):
    if 'log' not in request.session:
        request.session['log'] = []
    return render(request, "main_game/index.html", { 'player': Player.objects.last(), 'log': request.session['log'] })

def roll_dice(request):
    log = request.session['log']
    from random import randint
    die1 = randint(1, 6)
    log.append('first dice was: ' + str(die1))
    die2 = randint(1, 6)
    log.append('second dice was: ' + str(die2))
    log.append('total was: ' + str(die1 + die2))
    rolled = Field.objects.filter(number=die1 + die2)
    if len(rolled) == 0:
        log.append('no field matched the roll')
    else:
        for field in rolled:
            log.append('alloting resources for: ' + str(field.number) + " " + field.resource)
            messages = field.distribute_resources()
            if messages:
                log.append(*messages)
    request.session['log'] = log
    return redirect('/game')


def setup(request):
    request.session['currPlayer'] = request.session['player'][0]
    return redirect('/game')

def player_turn(request):
    print(request.session['player'])
    print(request.session['currPlayer'])
    for i in range(len(request.session['player'])):
        if request.session['player'][i] == request.session['currPlayer']:
            #print('player at i:', request.session['player'][i], 'current player:', request.session['currPlayer'])
            break
    #print("i is: ", i)
    if i == len(request.session['player']) - 1:
        request.session['currPlayer'] = request.session['player'][0]
        #print('current player is now:', request.session['currPlayer'])
    else:
        i += 1
        request.session['currPlayer'] = request.session['player'][i]
        #print('current player is now:', request.session['currPlayer'])
    return redirect('/game')

def purchase_settlement (request, settlement_id):
    # replace with current player
    player = Player.objects.get(id = request.session['currPlayer'])
    settlement = Settlement.objects.get(id= int(settlement_id))
    errors = settlement.purchase_settlement(player, False)
    if len(errors) == 0:
        player.brick -= 1
        player.lumber -= 1
        player.sheep -= 1
        player.wheat -= 1
        player.vic_points += 1
        player.save()
        settlement.player = player
        settlement.save()
        return redirect('/game')
    else:
        request.session['errors'] = errors
        print(*errors)
        return redirect('/game')

def purchase_road (request, road_id):
    # replace with current player
    player = Player.objects.get(id = request.session['currPlayer'])
    road = Road.objects.get(id = int(road_id))
    print("*" * 100)
    print(road)
    print(road.player)
    errors = road.purchase_road(player)
    if len(errors) == 0:
        player.brick -= 1
        player.lumber -= 1
        player.save()
        road.player = player
        road.save()
        return redirect('/game')
    else:
        request.session['errors'] = errors
        print(*errors)
        return redirect('/game')


def initialize_db(request):
    Field.objects.create(resource = 'lumber', robber=False, number = 11)
    Field.objects.create(resource = 'sheep', robber=False, number = 12)
    Field.objects.create(resource = 'wheat', robber=False, number = 9)
    Field.objects.create(resource = 'brick', robber=False, number = 4)
    Field.objects.create(resource = 'ore', robber=False, number = 6)
    Field.objects.create(resource = 'brick', robber=False, number = 5)
    Field.objects.create(resource = 'sheep', robber=False, number = 10)
    Field.objects.create(resource = 'lumber', robber=False, number = 3)
    Field.objects.create(resource = 'wheat', robber=False, number = 11)
    Field.objects.create(resource = 'lumber', robber=False, number = 4)
    Field.objects.create(resource = 'wheat', robber=False, number = 8)
    Field.objects.create(resource = 'brick', robber=False, number = 8)
    Field.objects.create(resource = 'sheep', robber=False, number = 10)
    Field.objects.create(resource = 'sheep', robber=False, number = 9)
    Field.objects.create(resource = 'ore', robber=False, number = 3)
    Field.objects.create(resource = 'ore', robber=False, number = 5)
    Field.objects.create(resource = 'wheat', robber=False, number = 2)
    Field.objects.create(resource = 'lumber', robber=False, number = 6)
    for i in range (1, 73):
        Road.objects.create()
    for i in range (1, 4):
        Settlement.objects.create()
    for i in range (1, 55):
        Settlement.objects.create()
    for i in range (1, 7):
        R = Road.objects.get(id=i)
        R.adjacent_settlements.add(Settlement.objects.get(id = (i+3)))
        R.save()
        R.adjacent_settlements.add(Settlement.objects.get(id = (i+4)))
        R.save()
    for i in range (11, 19):
        R = Road.objects.get(id = i)
        R.adjacent_settlements.add(Settlement.objects.get(id = i))
        R.save()
        R.adjacent_settlements.add(Settlement.objects.get(id = (i+1)))
        R.save()
    for i in range(23, 34):
        R = Road.objects.get(id = i)
        R.adjacent_settlements.add(Settlement.objects.get(id = (i-4)))
        R.save()
        R.adjacent_settlements.add(Settlement.objects.get(id = (i-3)))
        R.save()
    for i in range(41, 50):
        R = Road.objects.get(id = i)
        R.adjacent_settlements.add(Settlement.objects.get(id = (i - 10)))
        R.save()
        R.adjacent_settlements.add(Settlement.objects.get(id = (i - 9)))
        R.save()
    for i in range(55, 63):
        R = Road.objects.get(id = i)
        R.adjacent_settlements.add(Settlement.objects.get(id = (i - 14)))
        R.save()
        R.adjacent_settlements.add(Settlement.objects.get(id = (i - 13)))
    for i in range(67, 73):
        R = Road.objects.get(id = i)
        R.adjacent_settlements.add(Settlement.objects.get(id = (i-17)))
        R.save()
        R.adjacent_settlements.add(Settlement.objects.get(id = (i-16)))
        R.save()
    R = Road.objects.get(id = 7)
    R.adjacent_settlements.add(Settlement.objects.get(id = 4))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 12))
    R.save()
    R = Road.objects.get(id = 8)
    R.adjacent_settlements.add(Settlement.objects.get(id = 6))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 14))
    R.save()
    R = Road.objects.get(id = 9)
    R.adjacent_settlements.add(Settlement.objects.get(id = 8))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 16))
    R.save()
    R = Road.objects.get(id = 10)
    R.adjacent_settlements.add(Settlement.objects.get(id = 10))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 18))
    R.save()
    R = Road.objects.get(id = 19)
    R.adjacent_settlements.add(Settlement.objects.get(id = 11))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 21))
    R.save()
    R = Road.objects.get(id = 20)
    R.adjacent_settlements.add(Settlement.objects.get(id = 13))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 23))
    R.save()
    R = Road.objects.get(id = 21)
    R.adjacent_settlements.add(Settlement.objects.get(id = 15))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 25))
    R.save()
    R = Road.objects.get(id = 22)
    R.adjacent_settlements.add(Settlement.objects.get(id = 17))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 27))
    R.save()
    R = Road.objects.get(id = 34)
    R.adjacent_settlements.add(Settlement.objects.get(id = 20))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 57))
    R.save()
    R = Road.objects.get(id = 35)
    R.adjacent_settlements.add(Settlement.objects.get(id = 22))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 32))
    R.save()
    R = Road.objects.get(id = 36)
    R.adjacent_settlements.add(Settlement.objects.get(id = 24))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 34))
    R.save()
    R = Road.objects.get(id = 37)
    R.adjacent_settlements.add(Settlement.objects.get(id = 26))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 36))
    R.save()
    R = Road.objects.get(id = 38)
    R.adjacent_settlements.add(Settlement.objects.get(id = 28))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 38))
    R.save()
    R = Road.objects.get(id = 39)
    R.adjacent_settlements.add(Settlement.objects.get(id = 30))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 40))
    R.save()
    R = Road.objects.get(id = 40)
    R.adjacent_settlements.add(Settlement.objects.get(id = 31))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 57))
    R.save()
    R = Road.objects.get(id = 50)
    R.adjacent_settlements.add(Settlement.objects.get(id = 31))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 41))
    R.save()
    R = Road.objects.get(id = 51)
    R.adjacent_settlements.add(Settlement.objects.get(id = 33))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 43))
    R.save()
    R = Road.objects.get(id = 52)
    R.adjacent_settlements.add(Settlement.objects.get(id = 35))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 45))
    R.save()
    R = Road.objects.get(id = 53)
    R.adjacent_settlements.add(Settlement.objects.get(id = 37))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 47))
    R.save()
    R = Road.objects.get(id = 54)
    R.adjacent_settlements.add(Settlement.objects.get(id = 39))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 49))
    R.save()
    R = Road.objects.get(id = 63)
    R.adjacent_settlements.add(Settlement.objects.get(id = 42))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 50))
    R.save()
    R = Road.objects.get(id = 64)
    R.adjacent_settlements.add(Settlement.objects.get(id = 44))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 52))
    R.save()
    R = Road.objects.get(id = 65)
    R.adjacent_settlements.add(Settlement.objects.get(id = 46))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 54))
    R.save()
    R = Road.objects.get(id = 66)
    R.adjacent_settlements.add(Settlement.objects.get(id = 48))
    R.save()
    R.adjacent_settlements.add(Settlement.objects.get(id = 56))
    R.save()
    S = Settlement.objects.get(id = 4)
    S.adjacent_fields.add(Field.objects.get(id = 1))
    S.save()
    S = Settlement.objects.get(id = 5)
    S.adjacent_fields.add(Field.objects.get(id = 1))
    S.save()
    S = Settlement.objects.get(id = 6)
    S.adjacent_fields.add(Field.objects.get(id = 1))
    S.save()
    S = Settlement.objects.get(id = 6)
    S.adjacent_fields.add(Field.objects.get(id = 2))
    S.save()
    S = Settlement.objects.get(id = 7)
    S.adjacent_fields.add(Field.objects.get(id = 2))
    S.save()
    S = Settlement.objects.get(id = 8)
    S.adjacent_fields.add(Field.objects.get(id = 2))
    S.save()
    S = Settlement.objects.get(id = 8)
    S.adjacent_fields.add(Field.objects.get(id = 3))
    S.save()
    S = Settlement.objects.get(id = 9)
    S.adjacent_fields.add(Field.objects.get(id = 3))
    S.save()
    S = Settlement.objects.get(id = 10)
    S.adjacent_fields.add(Field.objects.get(id = 3))
    S.save()
    S = Settlement.objects.get(id = 11)
    S.adjacent_fields.add(Field.objects.get(id = 4))
    S.save()
    S = Settlement.objects.get(id = 12)
    S.adjacent_fields.add(Field.objects.get(id = 4))
    S.save()
    S = Settlement.objects.get(id = 12)
    S.adjacent_fields.add(Field.objects.get(id = 1))
    S.save()
    S = Settlement.objects.get(id = 13)
    S.adjacent_fields.add(Field.objects.get(id = 4))
    S.save()
    S = Settlement.objects.get(id = 13)
    S.adjacent_fields.add(Field.objects.get(id = 1))
    S.save()
    S = Settlement.objects.get(id = 13)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 14)
    S.adjacent_fields.add(Field.objects.get(id = 1))
    S.save()
    S = Settlement.objects.get(id = 14)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 14)
    S.adjacent_fields.add(Field.objects.get(id = 2))
    S.save()
    S = Settlement.objects.get(id = 15)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 15)
    S.adjacent_fields.add(Field.objects.get(id = 6))
    S.save()
    S = Settlement.objects.get(id = 15)
    S.adjacent_fields.add(Field.objects.get(id = 2))
    S.save()
    S = Settlement.objects.get(id = 16)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 16)
    S.adjacent_fields.add(Field.objects.get(id = 6))
    S.save()
    S = Settlement.objects.get(id = 16)
    S.adjacent_fields.add(Field.objects.get(id = 3))
    S.save()
    S = Settlement.objects.get(id = 17)
    S.adjacent_fields.add(Field.objects.get(id = 6))
    S.save()
    S = Settlement.objects.get(id = 17)
    S.adjacent_fields.add(Field.objects.get(id = 3))
    S.save()
    S = Settlement.objects.get(id = 17)
    S.adjacent_fields.add(Field.objects.get(id = 7))
    S.save()
    S = Settlement.objects.get(id = 18)
    S.adjacent_fields.add(Field.objects.get(id = 3))
    S.save()
    S = Settlement.objects.get(id = 18)
    S.adjacent_fields.add(Field.objects.get(id = 7))
    S.save()
    S = Settlement.objects.get(id = 19)
    S.adjacent_fields.add(Field.objects.get(id = 7))
    S.save()
    S = Settlement.objects.get(id = 21)
    S.adjacent_fields.add(Field.objects.get(id = 4))
    S.save()
    S = Settlement.objects.get(id = 22)
    S.adjacent_fields.add(Field.objects.get(id = 4))
    S.save()
    S = Settlement.objects.get(id = 22)
    S.adjacent_fields.add(Field.objects.get(id = 8))
    S.save()
    S = Settlement.objects.get(id = 23)
    S.adjacent_fields.add(Field.objects.get(id = 4))
    S.save()
    S = Settlement.objects.get(id = 23)
    S.adjacent_fields.add(Field.objects.get(id = 8))
    S.save()
    S = Settlement.objects.get(id = 23)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 24)
    S.adjacent_fields.add(Field.objects.get(id = 8))
    S.save()
    S = Settlement.objects.get(id = 24)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 24)
    S.adjacent_fields.add(Field.objects.get(id = 9))
    S.save()
    S = Settlement.objects.get(id = 25)
    S.adjacent_fields.add(Field.objects.get(id = 9))
    S.save()
    S = Settlement.objects.get(id = 25)
    S.adjacent_fields.add(Field.objects.get(id = 5))
    S.save()
    S = Settlement.objects.get(id = 25)
    S.adjacent_fields.add(Field.objects.get(id = 6))
    S.save()
    S = Settlement.objects.get(id = 26)
    S.adjacent_fields.add(Field.objects.get(id = 6))
    S.save()
    S = Settlement.objects.get(id = 26)
    S.adjacent_fields.add(Field.objects.get(id = 9))
    S.save()
    S = Settlement.objects.get(id = 26)
    S.adjacent_fields.add(Field.objects.get(id = 10))
    S.save()
    S = Settlement.objects.get(id = 27)
    S.adjacent_fields.add(Field.objects.get(id = 6))
    S.save()
    S = Settlement.objects.get(id = 27)
    S.adjacent_fields.add(Field.objects.get(id = 10))
    S.save()
    S = Settlement.objects.get(id = 27)
    S.adjacent_fields.add(Field.objects.get(id = 7))
    S.save()
    S = Settlement.objects.get(id = 28)
    S.adjacent_fields.add(Field.objects.get(id = 10))
    S.save()
    S = Settlement.objects.get(id = 28)
    S.adjacent_fields.add(Field.objects.get(id = 7))
    S.save()
    S = Settlement.objects.get(id = 28)
    S.adjacent_fields.add(Field.objects.get(id = 11))
    S.save()
    S = Settlement.objects.get(id = 29)
    S.adjacent_fields.add(Field.objects.get(id = 7))
    S.save()
    S = Settlement.objects.get(id = 29)
    S.adjacent_fields.add(Field.objects.get(id = 11))
    S.save()
    S = Settlement.objects.get(id = 30)
    S.adjacent_fields.add(Field.objects.get(id = 11))
    S.save()
    S = Settlement.objects.get(id = 31)
    S.adjacent_fields.add(Field.objects.get(id = 12))
    S.save()
    S = Settlement.objects.get(id = 32)
    S.adjacent_fields.add(Field.objects.get(id = 12))
    S.save()
    S = Settlement.objects.get(id = 32)
    S.adjacent_fields.add(Field.objects.get(id = 8))
    S.save()
    S = Settlement.objects.get(id = 33)
    S.adjacent_fields.add(Field.objects.get(id = 12))
    S.save()
    S = Settlement.objects.get(id = 33)
    S.adjacent_fields.add(Field.objects.get(id = 8))
    S.save()
    S = Settlement.objects.get(id = 33)
    S.adjacent_fields.add(Field.objects.get(id = 13))
    S.save()
    S = Settlement.objects.get(id = 34)
    S.adjacent_fields.add(Field.objects.get(id = 8))
    S.save()
    S = Settlement.objects.get(id = 34)
    S.adjacent_fields.add(Field.objects.get(id = 13))
    S.save()
    S = Settlement.objects.get(id = 34)
    S.adjacent_fields.add(Field.objects.get(id = 9))
    S.save()
    S = Settlement.objects.get(id = 35)
    S.adjacent_fields.add(Field.objects.get(id = 13))
    S.save()
    S = Settlement.objects.get(id = 35)
    S.adjacent_fields.add(Field.objects.get(id = 9))
    S.save()
    S = Settlement.objects.get(id = 35)
    S.adjacent_fields.add(Field.objects.get(id = 14))
    S.save()
    S = Settlement.objects.get(id = 36)
    S.adjacent_fields.add(Field.objects.get(id = 14))
    S.save()
    S = Settlement.objects.get(id = 36)
    S.adjacent_fields.add(Field.objects.get(id = 9))
    S.save()
    S = Settlement.objects.get(id = 36)
    S.adjacent_fields.add(Field.objects.get(id = 10))
    S.save()
    S = Settlement.objects.get(id = 37)
    S.adjacent_fields.add(Field.objects.get(id = 14))
    S.save()
    S = Settlement.objects.get(id = 37)
    S.adjacent_fields.add(Field.objects.get(id = 10))
    S.save()
    S = Settlement.objects.get(id = 37)
    S.adjacent_fields.add(Field.objects.get(id = 15))
    S.save()
    S = Settlement.objects.get(id = 38)
    S.adjacent_fields.add(Field.objects.get(id = 10))
    S.save()
    S = Settlement.objects.get(id = 38)
    S.adjacent_fields.add(Field.objects.get(id = 15))
    S.save()
    S = Settlement.objects.get(id = 38)
    S.adjacent_fields.add(Field.objects.get(id = 11))
    S.save()
    S = Settlement.objects.get(id = 39)
    S.adjacent_fields.add(Field.objects.get(id = 15))
    S.save()
    S = Settlement.objects.get(id = 39)
    S.adjacent_fields.add(Field.objects.get(id = 11))
    S.save()
    S = Settlement.objects.get(id = 40)
    S.adjacent_fields.add(Field.objects.get(id = 11))
    S.save()
    S = Settlement.objects.get(id = 41)
    S.adjacent_fields.add(Field.objects.get(id = 12))
    S.save()
    S = Settlement.objects.get(id = 42)
    S.adjacent_fields.add(Field.objects.get(id = 12))
    S.save()
    S = Settlement.objects.get(id = 42)
    S.adjacent_fields.add(Field.objects.get(id = 16))
    S.save()
    S = Settlement.objects.get(id = 43)
    S.adjacent_fields.add(Field.objects.get(id = 12))
    S.save()
    S = Settlement.objects.get(id = 43)
    S.adjacent_fields.add(Field.objects.get(id = 16))
    S.save()
    S = Settlement.objects.get(id = 43)
    S.adjacent_fields.add(Field.objects.get(id = 13))
    S.save()
    S = Settlement.objects.get(id = 44)
    S.adjacent_fields.add(Field.objects.get(id = 16))
    S.save()
    S = Settlement.objects.get(id = 44)
    S.adjacent_fields.add(Field.objects.get(id = 13))
    S.save()
    S = Settlement.objects.get(id = 44)
    S.adjacent_fields.add(Field.objects.get(id = 17))
    S.save()
    S = Settlement.objects.get(id = 45)
    S.adjacent_fields.add(Field.objects.get(id = 13))
    S.save()
    S = Settlement.objects.get(id = 45)
    S.adjacent_fields.add(Field.objects.get(id = 17))
    S.save()
    S = Settlement.objects.get(id = 45)
    S.adjacent_fields.add(Field.objects.get(id = 14))
    S.save()
    S = Settlement.objects.get(id = 46)
    S.adjacent_fields.add(Field.objects.get(id = 17))
    S.save()
    S = Settlement.objects.get(id = 46)
    S.adjacent_fields.add(Field.objects.get(id = 14))
    S.save()
    S = Settlement.objects.get(id = 46)
    S.adjacent_fields.add(Field.objects.get(id = 18))
    S.save()
    S = Settlement.objects.get(id = 47)
    S.adjacent_fields.add(Field.objects.get(id = 14))
    S.save()
    S = Settlement.objects.get(id = 47)
    S.adjacent_fields.add(Field.objects.get(id = 18))
    S.save()
    S = Settlement.objects.get(id = 47)
    S.adjacent_fields.add(Field.objects.get(id = 15))
    S.save()
    S = Settlement.objects.get(id = 48)
    S.adjacent_fields.add(Field.objects.get(id = 18))
    S.save()
    S = Settlement.objects.get(id = 48)
    S.adjacent_fields.add(Field.objects.get(id = 15))
    S.save()
    S = Settlement.objects.get(id = 49)
    S.adjacent_fields.add(Field.objects.get(id = 15))
    S.save()
    S = Settlement.objects.get(id = 50)
    S.adjacent_fields.add(Field.objects.get(id = 16))
    S.save()
    S = Settlement.objects.get(id = 51)
    S.adjacent_fields.add(Field.objects.get(id = 16))
    S.save()
    S = Settlement.objects.get(id = 52)
    S.adjacent_fields.add(Field.objects.get(id = 16))
    S.save()
    S = Settlement.objects.get(id = 52)
    S.adjacent_fields.add(Field.objects.get(id = 17))
    S.save()
    S = Settlement.objects.get(id = 53)
    S.adjacent_fields.add(Field.objects.get(id = 17))
    S.save()
    S = Settlement.objects.get(id = 54)
    S.adjacent_fields.add(Field.objects.get(id = 17))
    S.save()
    S = Settlement.objects.get(id = 54)
    S.adjacent_fields.add(Field.objects.get(id = 18))
    S.save()
    S = Settlement.objects.get(id = 55)
    S.adjacent_fields.add(Field.objects.get(id = 18))
    S.save()
    S = Settlement.objects.get(id = 56)
    S.adjacent_fields.add(Field.objects.get(id = 18))
    S.save()
    return redirect('/game')